version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - rm -f /etc/apt/sources.list.d/sbt.list
      - apt-get update
      - apt-get install -y awscli
      - npm install -g hexo-cli
      - npm install hexo-generator-sitemap --save
      - npm install


  build:
    commands:
      - hexo generate

  post_build:
    commands:
      - cd public/ && aws s3 sync . s3://blog.tdinvoke.net/
