# chan theme configuration

# site setting
rss: /atom.xml
favicon: https://blog.tdinvoke.net/images/favicon.ico

# style setting
monochrome: false

# view setting
avatar: https://en.gravatar.com/userimage/33595200/fd62856c01a5c58f02f4c0154eb2c2c0.png?size=200
avatarLink: /about
maxContentWidth: # set the main content column's max-width property. keep it blank to unlimited the width
copyright: # the copyright text in the footer, could be richtext

iconList: 
  - iconLink: https://github.com/tduong10101
    iconImgLink: https://blog.tdinvoke.net/images/github.svg
    iconImgLinkHover: https://blog.tdinvoke.net/images/github-hover.svg
  - iconLink: https://www.linkedin.com/in/terry-duong-a722b662
    iconImgLink: https://blog.tdinvoke.net/images/linkedin.svg
    iconImgLinkHover: https://blog.tdinvoke.net/images/linkedin-hover.svg
  - iconLink: https://blog.tdinvoke.net/random-podcast/
    iconImgLink: https://blog.tdinvoke.net/images/podcast.svg
    iconImgLinkHover: https://blog.tdinvoke.net/images/podcast-hover.svg
# sidebar navigator structure
# It's a list with item that is also list.
# The item of first level list means a group of links,
# and the item of the second level list means exactly a link.
# A link item is an object whit two properties: 'name' for displaying and 'link' for redirecting.
# A link starts with http/https would be rendered as a tag with 'target="_blank"' .
# There are also some special link items representing in string: 'categories', 'tags' and 'archives'
nav:
    - - name: Home
        url: "/"
      - name: About
        url: "/about"
    - - tags # display a collapsible tag list
      - archives # display a collapsible archive list
      - name: By Year
        url: /archives
# duoshuo shortname
# refer to http://duoshuo.com
# If you use disqus then you should set disqus_shortname in your site config and disable duoshuo here.
# You also need to set 'comments' to true in the front-matter
#duoshuo: sprabbit

# jiathis share id
# refer to http://jiathis.com
#jiathis: 1589291

# open graph
twitter:
google_plus:
fb_admins:
fb_app_id:

# analytics ids
google_analytics:
baidu_statistics:

# default creative commons
# There are 6 kinds of combination and place 'none' to disable.
# - by
# - by-sa
# - by-nd
# - by-nc
# - by-nc-sa
# - by-nc-nd
# - none
# This setting could be overwritten in the front matter of a post.
# More details in https://creativecommons.org
cc: by-sa

# FancyBox / PhotoSwipe
# Although it is called fancybox, we use PhotoSwipe instead.
# Check http://photoswipe.com
fancybox: true # enable fancybox/photoswipe rendering
# photoswipe: true  # the same
